version: '3.7'
services:
  jenkins:
    build: jenkins
    env_file:
      - jenkins.env
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jenkins/casc.yaml:/var/jenkins_home/casc.yaml

volumes:
  jenkins_home:
